version: '3'

services:
  medallion:
    image: medallion:0.3.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000

  mongo:
    image: mongo:4-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
